/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LanguagesRouteImport } from './routes/languages'
import { Route as DiseaseRouteImport } from './routes/disease'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CropsRouteImport } from './routes/crops'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiVoiceTtsRouteImport } from './routes/api/voice/tts'
import { Route as ApiVoiceTranscribeRouteImport } from './routes/api/voice/transcribe'
import { Route as ApiPublicNearbyRouteImport } from './routes/api/public/nearby'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguagesRoute = LanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseaseRoute = DiseaseRouteImport.update({
  id: '/disease',
  path: '/disease',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsRoute = CropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceTtsRoute = ApiVoiceTtsRouteImport.update({
  id: '/api/voice/tts',
  path: '/api/voice/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceTranscribeRoute = ApiVoiceTranscribeRouteImport.update({
  id: '/api/voice/transcribe',
  path: '/api/voice/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNearbyRoute = ApiPublicNearbyRouteImport.update({
  id: '/api/public/nearby',
  path: '/api/public/nearby',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/crops': typeof CropsRoute
  '/dashboard': typeof DashboardRoute
  '/disease': typeof DiseaseRoute
  '/languages': typeof LanguagesRoute
  '/market': typeof MarketRoute
  '/schemes': typeof SchemesRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/tips': typeof TipsRoute
  '/voice': typeof VoiceRoute
  '/weather': typeof WeatherRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/nearby': typeof ApiPublicNearbyRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
  '/api/voice/tts': typeof ApiVoiceTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/crops': typeof CropsRoute
  '/dashboard': typeof DashboardRoute
  '/disease': typeof DiseaseRoute
  '/languages': typeof LanguagesRoute
  '/market': typeof MarketRoute
  '/schemes': typeof SchemesRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/tips': typeof TipsRoute
  '/voice': typeof VoiceRoute
  '/weather': typeof WeatherRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/nearby': typeof ApiPublicNearbyRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
  '/api/voice/tts': typeof ApiVoiceTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/crops': typeof CropsRoute
  '/dashboard': typeof DashboardRoute
  '/disease': typeof DiseaseRoute
  '/languages': typeof LanguagesRoute
  '/market': typeof MarketRoute
  '/schemes': typeof SchemesRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/tips': typeof TipsRoute
  '/voice': typeof VoiceRoute
  '/weather': typeof WeatherRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/nearby': typeof ApiPublicNearbyRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
  '/api/voice/tts': typeof ApiVoiceTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/crops'
    | '/dashboard'
    | '/disease'
    | '/languages'
    | '/market'
    | '/schemes'
    | '/services'
    | '/testimonials'
    | '/tips'
    | '/voice'
    | '/weather'
    | '/api/chat'
    | '/api/public/nearby'
    | '/api/voice/transcribe'
    | '/api/voice/tts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/crops'
    | '/dashboard'
    | '/disease'
    | '/languages'
    | '/market'
    | '/schemes'
    | '/services'
    | '/testimonials'
    | '/tips'
    | '/voice'
    | '/weather'
    | '/api/chat'
    | '/api/public/nearby'
    | '/api/voice/transcribe'
    | '/api/voice/tts'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/crops'
    | '/dashboard'
    | '/disease'
    | '/languages'
    | '/market'
    | '/schemes'
    | '/services'
    | '/testimonials'
    | '/tips'
    | '/voice'
    | '/weather'
    | '/api/chat'
    | '/api/public/nearby'
    | '/api/voice/transcribe'
    | '/api/voice/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CropsRoute: typeof CropsRoute
  DashboardRoute: typeof DashboardRoute
  DiseaseRoute: typeof DiseaseRoute
  LanguagesRoute: typeof LanguagesRoute
  MarketRoute: typeof MarketRoute
  SchemesRoute: typeof SchemesRoute
  ServicesRoute: typeof ServicesRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TipsRoute: typeof TipsRoute
  VoiceRoute: typeof VoiceRoute
  WeatherRoute: typeof WeatherRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicNearbyRoute: typeof ApiPublicNearbyRoute
  ApiVoiceTranscribeRoute: typeof ApiVoiceTranscribeRoute
  ApiVoiceTtsRoute: typeof ApiVoiceTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/languages': {
      id: '/languages'
      path: '/languages'
      fullPath: '/languages'
      preLoaderRoute: typeof LanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease': {
      id: '/disease'
      path: '/disease'
      fullPath: '/disease'
      preLoaderRoute: typeof DiseaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops': {
      id: '/crops'
      path: '/crops'
      fullPath: '/crops'
      preLoaderRoute: typeof CropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/tts': {
      id: '/api/voice/tts'
      path: '/api/voice/tts'
      fullPath: '/api/voice/tts'
      preLoaderRoute: typeof ApiVoiceTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/transcribe': {
      id: '/api/voice/transcribe'
      path: '/api/voice/transcribe'
      fullPath: '/api/voice/transcribe'
      preLoaderRoute: typeof ApiVoiceTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nearby': {
      id: '/api/public/nearby'
      path: '/api/public/nearby'
      fullPath: '/api/public/nearby'
      preLoaderRoute: typeof ApiPublicNearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CropsRoute: CropsRoute,
  DashboardRoute: DashboardRoute,
  DiseaseRoute: DiseaseRoute,
  LanguagesRoute: LanguagesRoute,
  MarketRoute: MarketRoute,
  SchemesRoute: SchemesRoute,
  ServicesRoute: ServicesRoute,
  TestimonialsRoute: TestimonialsRoute,
  TipsRoute: TipsRoute,
  VoiceRoute: VoiceRoute,
  WeatherRoute: WeatherRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicNearbyRoute: ApiPublicNearbyRoute,
  ApiVoiceTranscribeRoute: ApiVoiceTranscribeRoute,
  ApiVoiceTtsRoute: ApiVoiceTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
